language: node_js
node_js:
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14

cache:
    npm: true
    directories:
        - node_modules

before_script:
    - npm run build

script:
    - npm run lint
    - npm run test
    - npm run coverage

after_success:
    - npm install -g coveralls && npm run coverage:report | coveralls

before_deploy:
    - npm ci
    - npm run build

deploy:
    provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_TOKEN
    on:
        tags: true
        node: 14
